version: '3.8'

services:
  glance:
    image: glanceapp/glance
    container_name: glance
    volumes:
      - ./glance.yml:/app/config/glance.yml
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8280:8080
    restart: unless-stopped
